config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'

  devise_for :users, skip: [:registrations, :sessions, :passwords]

  as :user do
    get 'users/register' => 'users/registrations#new', as: :new_user_registration
    post 'users/register' => 'users/registrations#create', as: :user_registration
    get 'users/login' => 'users/sessions#new', as: :new_user_session
    post 'users/login' => 'users/sessions#create', as: :user_session  
    delete 'users/logout'=> 'users/sessions#destroy', as: :destroy_user_session
    get 'users/:id/profile' => 'users/profile#edit', as: :edit_user_profile
    put 'users/:id/profile' => 'users/profile#update', as: :update_user_profile
  end

  resources :items, only: [:index, :show, :new, :edit, :create, :update]
  resources :categories, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true
  validates :encrypted_password, presence: true
  validates_confirmation_of :password

  devise :database_authenticatable, :registerable, :trackable
  enumerize :role, in: [:admin, :user], default: :user, predicates: true
  has_attached_file :avatar, styles: { small: "64x64>", medium: "128x128>", large: "512x512>" }, default_url: '/images/default_avatar_:style.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
      else
        session['devise.facebook_data'] = request.env['omniauth.auth']
        flash[:error] = @user.errors.full_messages
        redirect_to new_user_registration_url
      end
    end

    def failure
      redirect_to root_path
    end
  end
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < ApplicationController
  before_action :authenticate_user!
  layout 'without_sidebar'

  def edit
    @user = User.find(params[:id])
    authorize @user, :update?
  end

  def update
    @user = User.find(params[:id])
    authorize @user, :update?
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated.'
    else
      flash[:error] = @user.errors.full_messages
    end
    render 'edit'
  end

  protected

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :avatar).reject { |k,v| v.blank? }
    end

end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    include CommonHelper
    before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]
    layout 'without_sidebar'

    # GET /resource/sign_up
    def new
      flash.now[:event] = google_analytics_event_tracking('Register', 'Clicked')
      super
    end

    # POST /resource
    # def create
    #   super
    # end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout 'without_sidebar'

  # def new
  #   super
  # end

  # def create
  #   super
  # end

  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/users/profile/edit.html.erb
<!--  Avatar - Email - Name - Password - Password Confirmation -->
<div class="profile-panel panel panel-warning">
  <div class="panel-heading">
    <div class="panel-title">Update Profile</div>
  </div>
  <div class="panel-body">
    <%= form_for(@user, url: update_user_profile_path(@user), method: :put,
      html: { class:'form-horizontal', role: 'form' }) do |f| %>

      <div class="form-group text-center">
        <div class="col-md-12">
          <%= image_tag(current_user.avatar.url(:medium), height: '128', width: '128', alt: current_user.name) %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Email", class: 'col-md-3 control-label' %>
        <label class="col-md-9 content-label"><%= @user.email %></label>
      </div>

      <div class="form-group">
        <%= f.label :name, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name', required: "required" %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :password, 'New Password', class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.password_field :password, autocomplete: 'off', class: 'form-control', placeholder: 'New password' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.password_field :password_confirmation, autocomplete: 'off', class: 'form-control', placeholder: 'Password confirmation' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Avatar", class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.file_field(:avatar, class: 'form-control', accept: 'image/png,image/gif,image/jpeg') %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
          <%= f.submit 'Update', class: 'btn btn-info' %>
        </div>
      </div>

    <% end %>
  </div>
</div>