config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'

  devise_for :users, skip: [:registrations, :sessions, :passwords]

  as :user do
    get 'users/register' => 'users/registrations#new', as: :new_user_registration
    post 'users/register' => 'users/registrations#create', as: :user_registration
    get 'users/login' => 'users/sessions#new', as: :new_user_session
    post 'users/login' => 'users/sessions#create', as: :user_session  
    delete 'users/logout'=> 'users/sessions#destroy', as: :destroy_user_session
    get 'users/:id/profile' => 'users/profile#edit', as: :edit_user_profile
    put 'users/:id/profile' => 'users/profile#update', as: :update_user_profile
  end

  resources :items, only: [:index, :show, :new, :edit, :create, :update]
  resources :categories, only: [:show]
end

app/models/item.rb
require 'open-uri'

class Item < ApplicationRecord
  scope :newest, -> { order(created_at: :desc) }

  NEWEST_ITEMS_LIMIT = 4
  ITEMS_ON_ADMIN_PAGE = 10
  SEARCH_ITEMS_LIMIT = 10

  attr_accessor :import_quantity

  has_many :order_items, dependent: :destroy
  has_many :inventory_items, dependent: :destroy
  belongs_to :category
  delegate :category_name, to: :category

  validates :item_name, presence: true, length: { maximum: 255 }
  validates :category, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0.0 }

  after_save :solr_update_item, only: [:update]
  after_create :solr_push_item
  after_destroy :solr_destroy_item

  has_attached_file :item_image, styles: { small: '51x32>', medium: '71x38>', large: '110x86>' }
  validates_attachment_content_type :item_image, content_type: %r{\Aimage\/.*\z}

  def set_item_image_from_url(url)
    # Use to load image from Amazon
    self.item_image = open(url)
  end

  def sold_quantity
    inventory_items.sold.sum(:quantity)
  end

  def quantity
    inventory_items.imported.sum(:quantity) - sold_quantity
  end

  def import_item(quantity)
    return raise ArgumentError, 'Import quantity must greater than 0.' if quantity <= 0
    inventory_items.imported.create(quantity: quantity)
  end

  private

  def solr_update_item
    add_attributes = { allowDups: false, commitWithin: 10 }
    xml = $solr.xml.add(searchable, add_attributes)
    $solr.update(data: xml)
  end

  def solr_push_item
    $solr.add(searchable)
  end

  def solr_destroy_item
    $solr.delete_by_id(id)
  end

  def searchable
    {
      id: id,
      item_name: item_name,
      price: price
    }
  end
end

app/controllers/admin/items_controller.rb
module Admin
  class ItemsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_page_params, only: [:index]
    before_action :fetch_item, only: [:update]
    before_action -> { authorize(Item, :update?) }, only: [:index, :update]

    layout 'without_sidebar'

    def index
      @items = Item.newest.includes(:category).page(@page).per(Item::ITEMS_ON_ADMIN_PAGE)
    end

    def update
      if check_quantity
        if @item.import_item(item_params[:import_quantity].to_i)
          flash[:success] = "Import Item #{@item.item_name} successfully."
          return redirect_back(fallback_location: admin_items_path)
        end
      end
      flash[:error] = "Import Item #{@item.item_name} failed."
      redirect_back(fallback_location: admin_items_path)
    end

    private

    def fetch_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:import_quantity)
    end

    def check_quantity
      item_params[:import_quantity].blank? ||
        item_params[:import_quantity].to_i < 0
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    # Fetch Newest Items
    page = params[:page] || 1
    @items = Item.newest.page(page).per(Item::NEWEST_ITEMS_LIMIT)
    # Authorize with Pundit
    @items.each { |item| authorize item, :index? }
  end

  def show
    @item = Item.find_by_id(params[:id])
    return render 'items/_item_not_found' if @item.nil?
    authorize @item, :show?
    add_breadcrumb_for_item
  end

  def new
    @item = Item.new
    authorize @item, :create?
    add_breadcrumb_for_creating
  end

  def create
    @item = Item.new(item_params)
    authorize @item, :create?
    unless @item.save
      add_breadcrumb_for_creating
      flash[:error] = @item.errors.full_messages
      return render 'new'
    end
    flash[:success] = "Item was created successfully."
    add_breadcrumb_for_item
    render 'show'
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item, :update?
    add_breadcrumb_for_item
  end

  def update
    @item = Item.find(params[:id])
    authorize @item, :update?
    add_breadcrumb_for_item
    unless @item.update_attributes(item_params)
      flash[:error] = @item.errors.full_messages
      return render 'edit'
    end
    flash[:success] = "Item was updated successfully."
    render 'show'
  end

  private

    def item_params
      params.require(:item).permit(:item_name, :category_id, :price, :description, :item_image)
    end

    def add_breadcrumb_for_creating
      add_breadcrumb("Create New Item", new_item_path)
    end

    def add_breadcrumb_for_item
      add_breadcrumb(@item.category_name, category_path(@item.category))
      add_breadcrumb("Item ID #{@item.id}", item_path(@item))
    end

end

app/views/items/_form.html.erb
<%= form_for(item, html: { class:'form-horizontal', role: 'form' } ) do |f| %>

  <div class="form-group">
    <%= f.label :item_name, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :item_name, autofocus: true, class: 'form-control', placeholder: 'Item Name', required: "required" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :category_id, "Category", class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.collection_select :category_id, Category.order(:category_name), :id, :category_name,
        { include_blank: true }, { class: 'form-control', required: "required" }%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.number_field :price, class: 'form-control', placeholder: 'Price', step: 0.5, min: 0, required: "required" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_area :description, rows: 5, class: 'form-control', placeholder: 'Description' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Image", class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.file_field(:item_image, class: 'form-control', accept: 'image/png,image/gif,image/jpeg') %>
    </div>
  </div>

  <% if item.persisted? && item.item_image? %>
    <div class="form-group text-center">
      <div class="col-md-12">
        <%= image_tag(item.item_image.url(:medium), height: '38', width: '71', alt: item.item_name) %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-md-offset-3 col-md-9">
      <% if item.persisted?  %>
        <%= f.submit 'Update', class: 'btn btn-primary' %>
      <% else %>
        <%= f.submit 'Create', class: 'btn btn-info' %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/items/_item_not_found.html.erb
<%= render partial: 'shared/empty', locals: { message: 'The item you want to access was not found!' } %>

app/views/items/_order_form.html.erb
<%= form_for(order_item, remote: true) do |f| %>

  <div class="form-group">
    <span class="display-block">
      <label class="mg-r-5">Quantity want to buy:</label>
    </span>
    <%= f.number_field :quantity, class: 'form-control', placeholder: 'Quantity',
                                  step: 1, min: 1, required: 'required' %>
  </div>

  <%= f.hidden_field :item_id, value: order_item.item_id %>

  <div class="form-group">
    <%= f.submit "Add to Cart", class: "btn btn-primary"  %>
  </div>

<% end %>

<div id="orderMessagesHolder"></div>

app/views/items/edit.html.erb
<div class="item-panel panel panel-info">
  <div class="panel-heading">
    <div class="panel-title">Edit Item</div>
  </div>
  <div class="panel-body">
    <%= render partial: 'items/form', locals: { item: @item } %>
  </div>
</div>

app/views/items/index.html.erb
<h2 class="bg-primary heading-title">Newest Items</h2>
<% if @items.length.zero? %>
  <%= render partial: 'shared/empty', locals: { message: 'We don\'t have any items.' } %>
<% else %>
  <%= render partial: 'shared/horizontal_item', collection: @items, as: :item %>
<% end %>

<% set_meta_tags title: 'Home Page', reverse: true %>

app/views/items/new.html.erb
<div class="item-panel panel panel-info">
  <div class="panel-heading">
    <div class="panel-title">Create New Item</div>
  </div>
  <div class="panel-body">
    <%= render partial: 'items/form', locals: { item: @item } %>
  </div>
</div>

app/views/items/show.html.erb
<div class="item-page">
  <h2 class="text-danger"><%= @item.item_name %></h2>
  <div class="col-md-3 col-xs-12">
    <%= image_tag(@item.item_image.url(:large), height: '86', width: '110', alt: @item.item_name) %>
  </div>
  <div class="col-md-9 col-xs-12">
    <p>
      <span class="display-block">
        <label>Item ID:</label><%= @item.id %>
      </span>
      <span class="display-block">
        <label>Price:</label><%= @item.price %>
      </span>
      <span class="display-block">
        <label>Date Added:</label><%= @item.created_at.strftime('%m/%d/%Y') %>
      </span>
    </p>
    <% if policy(@item).update? %>
      <p>
        <%= link_to 'Edit', edit_item_path(@item), class: "btn btn-primary" %>
      </p>
    <% end %>
  </div>
  <div class="clearfix"></div>
  <hr/>
  <div class="col-md-12 col-xs-12 item-description">
    <% if @item.description? %>
      <p><%= raw @item.description.gsub(/\n/, '<br>') %></p>
    <% else %>
      <p>This Item don't have description.</p>
    <% end %>
  </div>
</div>