config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'

  devise_for :users, skip: [:registrations, :sessions, :passwords]

  as :user do
    get 'users/register' => 'users/registrations#new', as: :new_user_registration
    post 'users/register' => 'users/registrations#create', as: :user_registration
    get 'users/login' => 'users/sessions#new', as: :new_user_session
    post 'users/login' => 'users/sessions#create', as: :user_session  
    delete 'users/logout'=> 'users/sessions#destroy', as: :destroy_user_session
    get 'users/:id/profile' => 'users/profile#edit', as: :edit_user_profile
    put 'users/:id/profile' => 'users/profile#update', as: :update_user_profile
  end

  resources :items, only: [:index, :show, :new, :edit, :create, :update]
  resources :categories, only: [:show]
end

app/views/layouts/_cart_text.html.erb
<%= link_to(current_order.order_items.size.zero? ? 'Cart' : "#{pluralize(current_order.order_items.size, 'item')} in Cart",
  show_cart_path) %>

app/views/layouts/_head_tag.html.erb
<head>
  <%= display_meta_tags site: 'Venshop - Duong Vi Phat' %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-91389796-1', 'auto');
  </script>
  
  <% if Rails.env.production? %>
  <% end %>

</head>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="nav-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Project VenShop</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to 'Home', root_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Login</a></li>
        <li><a href="#">Register</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% unless f.empty? %>
  <% if f.first == 'event' %>
    <%= raw f.second %>
  <% else %>
    <div class="alert alert-<%= f.first.in?(['notice','success']) ? 'success' : 'danger' %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li><%= f.second %></li>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/layouts/_page_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted text-center">Copyright&copy;ZIGExN VeNtura - 2017</p>
  </div>
</footer>

app/views/layouts/_page_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="nav-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Project VenShop</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to 'Home', root_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if policy(Item).create? %>
            <li><%= link_to('Create New Item', new_item_path) %></li>
          <% end %>
          <li><%= link_to('Update Profile', edit_user_profile_path(current_user)) %></li>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li><%= link_to('Login', new_user_session_path) %></li>
          <li><%= link_to('Register', new_user_registration_path) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_search_form.html.erb
<%= form_tag search_path, :method => 'get' do %>
  <div class='col-md-offset-3 col-md-6 col-xs-12'>
    <div class='input-group col-md-12'>
      <%= text_field_tag :keyword, params[:keyword],
                          class: 'form-control input-lg', placeholder: 'Keyword' %>
      <span class='input-group-btn'>
        <%= submit_tag "Search", name: nil, class: 'btn btn-info btn-lg' %>
      </span>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<html>
  <%= render 'layouts/head_tag' %>
  <body>
    <%= render 'layouts/page_header' %>

    <div class="container">
      <div class="row mg-b-5">
        <%= render 'layouts/search_form' %>
      </div>
      <%= render partial: 'layouts/messages', collection: flash, as: :f %>
      <div class="row" id="breadcrumbs">
        <%= render_breadcrumbs %>
      </div>
      <div class="row">
        <div class="col-md-3 hidden-xs" id="sidebar"><%= CategoriesCell.() %></div>
        <div class="col-md-9 col-sm-12 col-xs-12"><%= yield %></div>
      </div>
    </div>
    <%= render 'layouts/page_footer' %>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=<%= ENV['FACEBOOK_APP_ID'] %>";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
  </body>
</html>
<% @category.nil? ? nil : set_meta_tags(
    title: "Category #{@category.category_name}",
    reverse: true
)%>

app/views/layouts/without_sidebar.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head_tag' %>

  <body>
    <%= render 'layouts/page_header' %>
    <div class="container">
      <%= render partial: 'layouts/messages', collection: flash, as: :f %>
      <div class="row">
        <div class="col-md-offset-3 col-md-6 col-xs-12"><%= yield %></div>
      </div>
    </div>
    <%= render 'layouts/page_footer' %>
  </body>
</html>